server:
  port: 8087
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.25.128
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8085/eureka
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
pubKeyPath: H:\rsa.pub # 公钥地址
cookieName: lyCookie